In [5]:
from sklearn.datasets import load_boston
import pandas as pd
import numpy as np

In [2]:
boston_dataset=load_boston()

c:\users\deepak\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
    dataset. You can load the datasets as follows::

        from sklearn.datasets import fetch_california_housing
        housing = fetch_california_housing()

    for the California housing dataset and::

        from sklearn.datasets import fetch_openml
        housing = fetch_openml(name="house_prices", as_frame=True)

    for the Ames housing dataset.

  warnings.warn(msg, category=FutureWarning)

In [6]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"  #error solution provided by jupyter itself
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [8]:
df = pd.DataFrame(boston_dataset.data,columns=boston_dataset.feature_names) #create dataframe
df['MEDV'] = boston_dataset.target  #set target variable i.e median value of owner occupied homes

In [9]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [10]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
x=df.loc[:,df.columns!='MEDV']
y=df.loc[:,df.columns=='MEDV']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [14]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
x_train=mms.fit_transform(x_train)
x_test=mms.transform(x_test)

In [18]:
#define our deep neural network
from keras.models import Sequential
from keras.layers import Dense

model=Sequential()

model.add(Dense(128,input_shape=(13,),activation='relu',name='dense_1')) #input layer with 128 neurons
model.add(Dense(64,activation='relu',name='dense_2')) #hidden layer with 64 neurons
model.add(Dense(1,activation='linear',name='deense_output')) #output layer

model.compile(optimizer='adam',loss='mse',metrics=['mae'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_1 (Dense)             (None, 128)               1792

 dense_2 (Dense)             (None, 64)                8256

 deense_output (Dense)       (None, 1)                 65

=================================================================
Total params: 10,113
Trainable params: 10,113
Non-trainable params: 0
_________________________________________________________________

In [19]:
#training model with help of training data
history=model.fit(x_train,y_train,epochs=100,verbose=1)

Epoch 1/100
12/12 [==============================] - 1s 6ms/step - loss: 607.9841 - mae: 22.8366
Epoch 2/100
12/12 [==============================] - 0s 4ms/step - loss: 561.0714 - mae: 21.7470
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 492.5869 - mae: 20.0347
Epoch 4/100
12/12 [==============================] - 0s 1ms/step - loss: 385.8210 - mae: 17.0127
Epoch 5/100
12/12 [==============================] - 0s 1ms/step - loss: 252.2338 - mae: 12.7652
Epoch 6/100
12/12 [==============================] - 0s 3ms/step - loss: 153.0329 - mae: 9.5562
Epoch 7/100
12/12 [==============================] - 0s 1ms/step - loss: 126.0159 - mae: 8.7125
Epoch 8/100
12/12 [==============================] - 0s 3ms/step - loss: 111.1335 - mae: 8.1508
Epoch 9/100
12/12 [==============================] - 0s 3ms/step - loss: 97.6335 - mae: 7.3495
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 87.8754 - mae: 6.8333
Epoch 11/100
12/12 [==============================] - 0s 2ms/step - loss: 78.8716 - mae: 6.6811
Epoch 12/100
12/12 [==============================] - 0s 3ms/step - loss: 72.7279 - mae: 6.3306
Epoch 13/100
12/12 [==============================] - 0s 2ms/step - loss: 67.1899 - mae: 5.9633
Epoch 14/100
12/12 [==============================] - 0s 2ms/step - loss: 62.7672 - mae: 5.7754
Epoch 15/100
12/12 [==============================] - 0s 3ms/step - loss: 59.6324 - mae: 5.7042
Epoch 16/100
12/12 [==============================] - 0s 2ms/step - loss: 57.0561 - mae: 5.4041
Epoch 17/100
12/12 [==============================] - 0s 1ms/step - loss: 55.2225 - mae: 5.4248
Epoch 18/100
12/12 [==============================] - 0s 2ms/step - loss: 53.7081 - mae: 5.3784
Epoch 19/100
12/12 [==============================] - 0s 2ms/step - loss: 51.5550 - mae: 5.0410
Epoch 20/100
12/12 [==============================] - 0s 2ms/step - loss: 50.1435 - mae: 4.9255
Epoch 21/100
12/12 [==============================] - 0s 3ms/step - loss: 49.2895 - mae: 5.1477
Epoch 22/100
12/12 [==============================] - 0s 2ms/step - loss: 46.8669 - mae: 4.9490
Epoch 23/100
12/12 [==============================] - 0s 1ms/step - loss: 45.9580 - mae: 4.6567
Epoch 24/100
12/12 [==============================] - 0s 2ms/step - loss: 44.3048 - mae: 4.6369
Epoch 25/100
12/12 [==============================] - 0s 3ms/step - loss: 42.7037 - mae: 4.6463
Epoch 26/100
12/12 [==============================] - 0s 1ms/step - loss: 41.3696 - mae: 4.5949
Epoch 27/100
12/12 [==============================] - 0s 2ms/step - loss: 40.0379 - mae: 4.4663
Epoch 28/100
12/12 [==============================] - 0s 3ms/step - loss: 39.3418 - mae: 4.6068
Epoch 29/100
12/12 [==============================] - 0s 3ms/step - loss: 37.8675 - mae: 4.3860
Epoch 30/100
12/12 [==============================] - 0s 1ms/step - loss: 36.9060 - mae: 4.1392
Epoch 31/100
12/12 [==============================] - 0s 2ms/step - loss: 35.4699 - mae: 4.0867
Epoch 32/100
12/12 [==============================] - 0s 2ms/step - loss: 34.2308 - mae: 4.0649
Epoch 33/100
12/12 [==============================] - 0s 3ms/step - loss: 33.2363 - mae: 3.9595
Epoch 34/100
12/12 [==============================] - 0s 1ms/step - loss: 32.4780 - mae: 3.9942
Epoch 35/100
12/12 [==============================] - 0s 3ms/step - loss: 31.4715 - mae: 3.9433
Epoch 36/100
12/12 [==============================] - 0s 3ms/step - loss: 30.6227 - mae: 3.8072
Epoch 37/100
12/12 [==============================] - 0s 2ms/step - loss: 29.6737 - mae: 3.7617
Epoch 38/100
12/12 [==============================] - 0s 3ms/step - loss: 29.0008 - mae: 3.6700
Epoch 39/100
12/12 [==============================] - 0s 1ms/step - loss: 28.2992 - mae: 3.7338
Epoch 40/100
12/12 [==============================] - 0s 2ms/step - loss: 27.1931 - mae: 3.5627
Epoch 41/100
12/12 [==============================] - 0s 2ms/step - loss: 26.8126 - mae: 3.5978
Epoch 42/100
12/12 [==============================] - 0s 3ms/step - loss: 25.9861 - mae: 3.4428
Epoch 43/100
12/12 [==============================] - 0s 3ms/step - loss: 25.2808 - mae: 3.3611
Epoch 44/100
12/12 [==============================] - 0s 3ms/step - loss: 24.6784 - mae: 3.3531
Epoch 45/100
12/12 [==============================] - 0s 2ms/step - loss: 24.5592 - mae: 3.3156
Epoch 46/100
12/12 [==============================] - 0s 3ms/step - loss: 23.8638 - mae: 3.2684
Epoch 47/100
12/12 [==============================] - 0s 3ms/step - loss: 24.3047 - mae: 3.4177
Epoch 48/100
12/12 [==============================] - 0s 2ms/step - loss: 23.2912 - mae: 3.1789
Epoch 49/100
12/12 [==============================] - 0s 2ms/step - loss: 23.7492 - mae: 3.4656
Epoch 50/100
12/12 [==============================] - 0s 1ms/step - loss: 22.4985 - mae: 3.1904
Epoch 51/100
12/12 [==============================] - 0s 2ms/step - loss: 22.3835 - mae: 3.1578
Epoch 52/100
12/12 [==============================] - 0s 3ms/step - loss: 22.9558 - mae: 3.1318
Epoch 53/100
12/12 [==============================] - 0s 2ms/step - loss: 22.3265 - mae: 3.2598
Epoch 54/100
12/12 [==============================] - 0s 2ms/step - loss: 22.2897 - mae: 3.0948
Epoch 55/100
12/12 [==============================] - 0s 1ms/step - loss: 21.4152 - mae: 3.0865
Epoch 56/100
12/12 [==============================] - 0s 2ms/step - loss: 21.4804 - mae: 3.1466
Epoch 57/100
12/12 [==============================] - 0s 3ms/step - loss: 21.1101 - mae: 3.1736
Epoch 58/100
12/12 [==============================] - 0s 3ms/step - loss: 21.5774 - mae: 3.1044
Epoch 59/100
12/12 [==============================] - 0s 1ms/step - loss: 21.7322 - mae: 3.2217
Epoch 60/100
12/12 [==============================] - 0s 2ms/step - loss: 20.5392 - mae: 3.0303
Epoch 61/100
12/12 [==============================] - 0s 2ms/step - loss: 20.3892 - mae: 3.0360
Epoch 62/100
12/12 [==============================] - 0s 2ms/step - loss: 21.3351 - mae: 3.2891
Epoch 63/100
12/12 [==============================] - 0s 1ms/step - loss: 19.9224 - mae: 2.9554
Epoch 64/100
12/12 [==============================] - 0s 2ms/step - loss: 19.7701 - mae: 2.9396
Epoch 65/100
12/12 [==============================] - 0s 3ms/step - loss: 19.7450 - mae: 3.0172
Epoch 66/100
12/12 [==============================] - 0s 3ms/step - loss: 19.4692 - mae: 2.9754
Epoch 67/100
12/12 [==============================] - 0s 2ms/step - loss: 19.4270 - mae: 2.9789
Epoch 68/100
12/12 [==============================] - 0s 2ms/step - loss: 19.5018 - mae: 2.9052
Epoch 69/100
12/12 [==============================] - 0s 3ms/step - loss: 19.1728 - mae: 2.9001
Epoch 70/100
12/12 [==============================] - 0s 3ms/step - loss: 19.4744 - mae: 3.0339
Epoch 71/100
12/12 [==============================] - 0s 2ms/step - loss: 19.4212 - mae: 2.9198
Epoch 72/100
12/12 [==============================] - 0s 1ms/step - loss: 18.7753 - mae: 2.8886
Epoch 73/100
12/12 [==============================] - 0s 2ms/step - loss: 22.3689 - mae: 3.5702
Epoch 74/100
12/12 [==============================] - 0s 3ms/step - loss: 19.4373 - mae: 3.0316
Epoch 75/100
12/12 [==============================] - 0s 2ms/step - loss: 18.3436 - mae: 2.9421
Epoch 76/100
12/12 [==============================] - 0s 2ms/step - loss: 18.3891 - mae: 2.8955
Epoch 77/100
12/12 [==============================] - 0s 3ms/step - loss: 18.0703 - mae: 2.8992
Epoch 78/100
12/12 [==============================] - 0s 1ms/step - loss: 18.1640 - mae: 2.8910
Epoch 79/100
12/12 [==============================] - 0s 2ms/step - loss: 18.0107 - mae: 2.8330
Epoch 80/100
12/12 [==============================] - 0s 3ms/step - loss: 18.2569 - mae: 2.9967
Epoch 81/100
12/12 [==============================] - 0s 3ms/step - loss: 17.6094 - mae: 2.8302
Epoch 82/100
12/12 [==============================] - 0s 2ms/step - loss: 17.4236 - mae: 2.8346
Epoch 83/100
12/12 [==============================] - 0s 2ms/step - loss: 17.2327 - mae: 2.7950
Epoch 84/100
12/12 [==============================] - 0s 3ms/step - loss: 17.1599 - mae: 2.7635
Epoch 85/100
12/12 [==============================] - 0s 3ms/step - loss: 16.9859 - mae: 2.7586
Epoch 86/100

12/12 [==============================] - 0s 3ms/step - loss: 17.0549 - mae: 2.8225
Epoch 87/100
12/12 [==============================] - 0s 2ms/step - loss: 16.9541 - mae: 2.7438
Epoch 88/100
12/12 [==============================] - 0s 1ms/step - loss: 17.6023 - mae: 2.9118
Epoch 89/100
12/12 [==============================] - 0s 1ms/step - loss: 16.7148 - mae: 2.7252
Epoch 90/100
12/12 [==============================] - 0s 2ms/step - loss: 16.8270 - mae: 2.7465
Epoch 91/100
12/12 [==============================] - 0s 2ms/step - loss: 16.6014 - mae: 2.6846
Epoch 92/100
12/12 [==============================] - 0s 1ms/step - loss: 16.2044 - mae: 2.7029
Epoch 93/100
12/12 [==============================] - 0s 2ms/step - loss: 16.2744 - mae: 2.7474
Epoch 94/100
12/12 [==============================] - 0s 2ms/step - loss: 16.2332 - mae: 2.6446
Epoch 95/100
12/12 [==============================] - 0s 2ms/step - loss: 16.1903 - mae: 2.6475
Epoch 96/100
12/12 [==============================] - 0s 3ms/step - loss: 15.8699 - mae: 2.6789
Epoch 97/100
12/12 [==============================] - 0s 3ms/step - loss: 15.8209 - mae: 2.6330
Epoch 98/100
12/12 [==============================] - 0s 2ms/step - loss: 16.0217 - mae: 2.7283
Epoch 99/100
12/12 [==============================] - 0s 2ms/step - loss: 15.7445 - mae: 2.6084
Epoch 100/100
12/12 [==============================] - 0s 2ms/step - loss: 15.6778 - mae: 2.7067

In [20]:
#evaluate model on testing data
mse,mae=model.evaluate(x_test,y_test)
print('MSE : ',mse)
print('MAE : ',mae)

5/5 [==============================] - 0s 5ms/step - loss: 11.8157 - mae: 2.6294
MSE :  11.815712928771973
MAE :  2.629361391067505

In [23]:
#make predictions on new data
y_test

     MEDV
418   8.8
436   9.6
82   24.8
280  45.4
399   6.3
..    ...
187  32.0
450  13.4
127  16.2
456  12.7
31   14.5

[152 rows x 1 columns]

In [24]:
y1=model.predict(x_test[:])

5/5 [==============================] - 0s 5ms/step

In [28]:
ps=[]
for i in y1:
    ps.append(list(i)[0])

In [33]:
d=pd.DataFrame({'Actual':y_test['MEDV'],'Predicted:ps'})

SyntaxError: invalid syntax (1454840138.py, line 1)

In [31]:
d

     Actual  Predicted
418     8.8   7.368261
436     9.6  13.594621
82     24.8  25.172426
280    45.4  42.125614
399     6.3  11.594234
..      ...        ...
187    32.0  32.203957
450    13.4  15.325657
127    16.2  16.894756
456    12.7  13.711789
31     14.5  19.132120

[152 rows x 2 columns]